/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Errors_CONSTANTS_H
#define Errors_CONSTANTS_H

#include "Errors_types.h"

namespace evernote { namespace edam {

class ErrorsConstants {
 public:
  ErrorsConstants();

};

extern const ErrorsConstants g_Errors_constants;

}} // namespace

#endif
