/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Errors_constants.h"

namespace evernote { namespace edam {

const ErrorsConstants g_Errors_constants;

ErrorsConstants::ErrorsConstants() {
}

}} // namespace

