/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "NoteStore_constants.h"

namespace evernote { namespace edam {

const NoteStoreConstants g_NoteStore_constants;

NoteStoreConstants::NoteStoreConstants() {
}

}} // namespace

