/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NoteStore_CONSTANTS_H
#define NoteStore_CONSTANTS_H

#include "NoteStore_types.h"

namespace evernote { namespace edam {

class NoteStoreConstants {
 public:
  NoteStoreConstants();

};

extern const NoteStoreConstants g_NoteStore_constants;

}} // namespace

#endif
