/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "UserStore_constants.h"

namespace evernote { namespace edam {

const UserStoreConstants g_UserStore_constants;

UserStoreConstants::UserStoreConstants() {
  EDAM_VERSION_MAJOR = 1;

  EDAM_VERSION_MINOR = 28;

}

}} // namespace

