/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef UserStore_CONSTANTS_H
#define UserStore_CONSTANTS_H

#include "UserStore_types.h"

namespace evernote { namespace edam {

class UserStoreConstants {
 public:
  UserStoreConstants();

  int16_t EDAM_VERSION_MAJOR;
  int16_t EDAM_VERSION_MINOR;
};

extern const UserStoreConstants g_UserStore_constants;

}} // namespace

#endif
